"""add_chat_summary

Revision ID: 4977846c45a6
Revises: 92b3bcd1add3
Create Date: 2026-09-12 16:09:54.385619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4977846c45a6'
down_revision: Union[str, Sequence[str], None] = '92b3bcd1add3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('key_topics', sa.String(length=500), nullable=True))
    op.add_column('chats', sa.Column('summarized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'summarized_at')
    op.drop_column('chats', 'key_topics')
    op.drop_column('chats', 'summary')
    # ### end Alembic commands ###
