"""add_user_preferences

Revision ID: 92b3bcd1add3
Revises: b3033e94c24c
Create Date: 2026-09-12 16:01:38.268538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b3bcd1add3'
down_revision: Union[str, Sequence[str], None] = 'b3033e94c24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('response_style', sa.String(length=16), nullable=False),
    sa.Column('formality', sa.String(length=16), nullable=False),
    sa.Column('expertise_level', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
