"""add_message_feedback

Revision ID: b3033e94c24c
Revises: c20ebb48dbfe
Create Date: 2026-09-12 13:51:59.792341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3033e94c24c'
down_revision: Union[str, Sequence[str], None] = 'c20ebb48dbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sa.String(length=8), nullable=True))
    op.add_column('messages', sa.Column('feedback_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback_note')
    op.drop_column('messages', 'feedback')
    # ### end Alembic commands ###
